specVersion: 0.2.0
name: withdraw-subql
version: 1.0.0
description: The project is for user to have ability to withdraw from Parallel
repository: "https://github.com/parallel-finance/withdraw-subql"
schema:
  file: ./schema.graphql
network:
  genesisHash: "0x6c6f83cc4d24cca4baf440f6d1b47dfc4059f3a7c0cab42d97cc81914a54ef4a"
  endpoint: "wss://regnet2-rpc.parallel.fi"
dataSources:
  - kind: substrate/Runtime
    startBlock: 98640
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBatchAll
          kind: substrate/CallHandler
          filter:
            module: utility
            method: batchAll
            success: true
